version: '3.7'
services:
  bookstore:
    container_name: eregistracija
    build: .
    image: eregistracija:latest
    ports:
      - 80:8080
    networks:
      - eregistracija-network
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    networks:
      - eregistracija-network
    environment:
      - MYSQL_ROOT_PASSWORD=lozinka
      - MYSQL_DATABASE=eregistracija
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data:
networks:
  eregistracija-network:
    driver: bridge